In [1]:
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
# 학습 데이터 생성
train_data = np.random.randint(0, 10, size = (10000, 5))
label_data = np.flip(train_data, axis = 1)
print(train_data[:4])
print(label_data[:4])

[[7 1 3 3 3]
 [2 4 5 5 9]
 [4 2 7 8 4]
 [4 9 5 0 7]]
[[3 3 3 1 7]
 [9 5 5 4 2]
 [4 8 7 2 4]
 [7 0 5 9 4]]


In [3]:
padded_train = pad_sequences(train_data, maxlen = 5)
print(padded_train[0])

[7 1 3 3 3]


In [4]:
# 모델링
model = Sequential()
model.add(Embedding(10, 100, input_length = 5))
model.add(Bidirectional(LSTM(64, return_sequences = True)))
model.add(Dense(10, activation = 'softmax'))

In [5]:
# 모델 요약
model.build(input_shape = (None, 5))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 100)            1000      
                                                                 
 bidirectional (Bidirectiona  (None, 5, 128)           84480     
 l)                                                              
                                                                 
 dense (Dense)               (None, 5, 10)             1290      
                                                                 
Total params: 86,770
Trainable params: 86,770
Non-trainable params: 0
_________________________________________________________________


In [6]:
# 모델 컴파일
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [7]:
# 모델 실행
history = model.fit(padded_train, label_data, epochs = 10, batch_size = 32, validation_split = 0.2)

Epoch 1/10
250/250 [==============================] - 3s 7ms/step - loss: 1.4927 - accuracy: 0.4459 - val_loss: 1.0622 - val_accuracy: 0.5356
Epoch 2/10
250/250 [==============================] - 1s 6ms/step - loss: 0.9924 - accuracy: 0.5592 - val_loss: 0.9238 - val_accuracy: 0.5798
Epoch 3/10
250/250 [==============================] - 1s 6ms/step - loss: 0.8774 - accuracy: 0.5957 - val_loss: 0.8369 - val_accuracy: 0.6173
Epoch 4/10
250/250 [==============================] - 2s 6ms/step - loss: 0.7693 - accuracy: 0.6522 - val_loss: 0.7163 - val_accuracy: 0.6892
Epoch 5/10
250/250 [==============================] - 2s 7ms/step - loss: 0.6569 - accuracy: 0.7279 - val_loss: 0.6043 - val_accuracy: 0.7581
Epoch 6/10
250/250 [==============================] - 2s 7ms/step - loss: 0.5332 - accuracy: 0.8062 - val_loss: 0.4728 - val_accuracy: 0.8345
Epoch 7/10
250/250 [==============================] - 2s 7ms/step - loss: 0.4038 - accuracy: 0.8700 - val_loss: 0.3622 - val_accuracy: 0.8803
Epoch 

In [8]:
# loss와 accuracy
loss, acc = model.evaluate(padded_train, label_data)
print(f"loss : {loss: .4f}, acc = {acc: .4f}")

313/313 [==============================] - 1s 4ms/step - loss: 0.1097 - accuracy: 0.9792
loss :  0.1097, acc =  0.9792


In [9]:
# 입력받아 예측하는 프로그램 작성
while True:
    user = input("0~9 사이의 숫자 5개 또는 Quit: ")
    if user == 'Quit':
        print("종료합니다")
        break
    numbers = list(map(int, user.split()))
    array_numbers = np.array([numbers])
    padded_numbers = pad_sequences(array_numbers, maxlen = 5)
    prediction = model.predict(padded_numbers)
    print(np.argmax(prediction, axis = -1)[0])

1/1 [==============================] - 0s 351ms/step
[0 0 0 0 0]
1/1 [==============================] - 0s 15ms/step
[0 0 0 0 0]


ValueError: invalid literal for int() with base 10: 'qㅕㅑㅅ'