In [1]:
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
# 학습 데이터 생성
train_data = np.random.randint(0, 10, size = (10000, 5))
label_data = np.flip(train_data, axis = 1)
print(train_data[:4])
print(label_data[:4])

[[1 3 9 1 5]
 [8 0 9 4 5]
 [7 5 8 1 8]
 [7 3 1 2 3]]
[[5 1 9 3 1]
 [5 4 9 0 8]
 [8 1 8 5 7]
 [3 2 1 3 7]]


In [3]:
# pad_sequence 전처리
padded_train = pad_sequences(train_data, maxlen = 5)
print(padded_train[0])

[1 3 9 1 5]


In [4]:
# 모델링
model = Sequential()
model.add(Embedding(10, 100, input_length = 5))
model.add(Bidirectional(LSTM(64, return_sequences = True)))
model.add(Dense(10, activation = 'softmax'))

In [5]:
# 모델 요약
model.build(input_shape = (None, 5))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 100)            1000      
                                                                 
 bidirectional (Bidirectiona  (None, 5, 128)           84480     
 l)                                                              
                                                                 
 dense (Dense)               (None, 5, 10)             1290      
                                                                 
Total params: 86,770
Trainable params: 86,770
Non-trainable params: 0
_________________________________________________________________


In [6]:
# 모델 컴파일
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [7]:
# 모델 실행
history = model.fit(padded_train, label_data, epochs = 10, batch_size = 32, validation_split = 0.2)

Epoch 1/10
250/250 [==============================] - 20s 38ms/step - loss: 1.4987 - accuracy: 0.4412 - val_loss: 1.0651 - val_accuracy: 0.5389
Epoch 2/10
250/250 [==============================] - 5s 21ms/step - loss: 0.9917 - accuracy: 0.5582 - val_loss: 0.9266 - val_accuracy: 0.5805
Epoch 3/10
250/250 [==============================] - 5s 21ms/step - loss: 0.8768 - accuracy: 0.5997 - val_loss: 0.8346 - val_accuracy: 0.6214
Epoch 4/10
250/250 [==============================] - 6s 22ms/step - loss: 0.7672 - accuracy: 0.6611 - val_loss: 0.7334 - val_accuracy: 0.6792
Epoch 5/10
250/250 [==============================] - 4s 14ms/step - loss: 0.6503 - accuracy: 0.7380 - val_loss: 0.6094 - val_accuracy: 0.7636
Epoch 6/10
250/250 [==============================] - 3s 11ms/step - loss: 0.5213 - accuracy: 0.8134 - val_loss: 0.4820 - val_accuracy: 0.8277
Epoch 7/10
250/250 [==============================] - 3s 12ms/step - loss: 0.3988 - accuracy: 0.8717 - val_loss: 0.3604 - val_accuracy: 0.887

In [8]:
# loss와 accuracy
loss, acc = model.evaluate(padded_train, label_data)
print(f"loss : {loss: .4f}, acc = {acc: .4f}")

313/313 [==============================] - 3s 8ms/step - loss: 0.1012 - accuracy: 0.9814
loss :  0.1012, acc =  0.9814


In [11]:
# 입력받아 예측하는 프로그램 작성
while True:
    user = input("0~9 사이의 숫자 5개 또는 Quit: ")
    if user == 'Quit':
        print("종료합니다")
        break
    numbers = list(map(int, user.split()))
    array_numbers = np.array([numbers])
    padded_numbers = pad_sequences(array_numbers, maxlen = 5)
    prediction = model.predict(padded_numbers)
    print(np.argmax(prediction, axis = -1)[0])

1/1 [==============================] - 0s 37ms/step
[5 4 3 2 1]
1/1 [==============================] - 0s 49ms/step
[5 7 8 6 5]
종료합니다
