In [22]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

In [23]:
learning_rate = 0.01
tf.set_random_seed(0)
np.random.seed(0)

In [24]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype = np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype = np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 5]), name = 'weight1')
b1 = tf.Variable(tf.random_normal([5]), name = 'bias1')

W2 = tf.Variable(tf.random_normal([5, 5]), name = 'weight2')
b2 = tf.Variable(tf.random_normal([5]), name = 'bias2')

W3 = tf.Variable(tf.random_normal([5, 5]), name = 'weight3')
b3 = tf.Variable(tf.random_normal([5]), name = 'bias3')

W4 = tf.Variable(tf.random_normal([5, 5]), name = 'weight4')
b4 = tf.Variable(tf.random_normal([5]), name = 'bias4')

W5 = tf.Variable(tf.random_normal([5, 5]), name = 'weight5')
b5 = tf.Variable(tf.random_normal([5]), name = 'bias5')

W6 = tf.Variable(tf.random_normal([5, 5]), name = 'weight6')
b6 = tf.Variable(tf.random_normal([5]), name = 'bias6')

W7 = tf.Variable(tf.random_normal([5, 5]), name = 'weight7')
b7 = tf.Variable(tf.random_normal([5]), name = 'bias7')

W8 = tf.Variable(tf.random_normal([5, 5]), name = 'weight8')
b8 = tf.Variable(tf.random_normal([5]), name = 'bias8')

W9 = tf.Variable(tf.random_normal([5, 5]), name = 'weight9')
b9 = tf.Variable(tf.random_normal([5]), name = 'bias9')

W10 = tf.Variable(tf.random_normal([5, 1]), name = 'weight10')
b10 = tf.Variable(tf.random_normal([1]), name = 'bias10')

In [25]:
def hypothesis():
    layer1 = tf.sigmoid(tf.matmul(x_data, W1) + b1)
    layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)
    layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)
    layer4 = tf.sigmoid(tf.matmul(layer3, W4) + b4)
    layer5 = tf.sigmoid(tf.matmul(layer4, W5) + b5)
    layer6 = tf.sigmoid(tf.matmul(layer5, W6) + b6)
    layer7 = tf.sigmoid(tf.matmul(layer6, W7) + b7)
    layer8 = tf.sigmoid(tf.matmul(layer7, W8) + b8)
    layer9 = tf.sigmoid(tf.matmul(layer8, W9) + b9)
    cost = tf.sigmoid(tf.matmul(layer9, W10) + b10)

    return cost
    

In [26]:
cost = -tf.reduce_mean(y_data * tf.log(hypothesis()) + (1 - y_data) * tf.log(1 - hypothesis()))
train = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [27]:
predicted = tf.cast(hypothesis() > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, y_data), dtype = tf.float32))

In [28]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(1001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})

        if step % 100 == 0:
            print("step = ", step, "cost = ", sess.run(cost, feed_dict = {X: x_data, Y: y_data}),sess.run(W2))
    h, c, a = sess.run([hypothesis(), predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
    print("\nAccuracy: ", a)

step =  0 cost =  0.7825508 [[-0.73173314  0.4741495   0.24105729  2.058107   -0.5132378 ]
 [ 0.6171242   0.7645921   0.3361333   1.577778   -0.9244262 ]
 [-0.37950546  1.060116    0.4725261  -0.06256945  2.2003388 ]
 [-0.83873355 -1.1596988   0.27424526  0.44216737  0.0126053 ]
 [ 1.0290936   0.76141894  0.22197531  1.0325111  -0.82623076]]
step =  100 cost =  0.7121546 [[-0.73173314  0.4741458   0.2410558   2.058107   -0.5132325 ]
 [ 0.6171242   0.76456785  0.33612612  1.577778   -0.9244025 ]
 [-0.37950844  1.0600921   0.47251913 -0.06256941  2.2003627 ]
 [-0.83873504 -1.1597334   0.27423525  0.44216737  0.01263968]
 [ 1.0290936   0.7613944   0.22196844  1.0325111  -0.8262052 ]]
step =  200 cost =  0.6969451 [[-0.73173314  0.47414362  0.24105576  2.058107   -0.5132325 ]
 [ 0.6171242   0.7645565   0.33612275  1.577778   -0.9243915 ]
 [-0.3795086   1.0600802   0.4725161  -0.06256941  2.2003736 ]
 [-0.83873504 -1.1597499   0.27423045  0.44216737  0.01265644]
 [ 1.0290936   0.76138365  0