In [15]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

In [16]:
learning_rate = 0.01
tf.set_random_seed(0)
np.random.seed(0)

In [17]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype = np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype = np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 5]), name = 'weight1')
b1 = tf.Variable(tf.random_normal([5]), name = 'bias1')

W2 = tf.Variable(tf.random_normal([5, 5]), name = 'weight2')
b2 = tf.Variable(tf.random_normal([5]), name = 'bias2')

W3 = tf.Variable(tf.random_normal([5, 5]), name = 'weight3')
b3 = tf.Variable(tf.random_normal([5]), name = 'bias3')

W4 = tf.Variable(tf.random_normal([5, 5]), name = 'weight4')
b4 = tf.Variable(tf.random_normal([5]), name = 'bias4')

W5 = tf.Variable(tf.random_normal([5, 5]), name = 'weight5')
b5 = tf.Variable(tf.random_normal([5]), name = 'bias5')

W6 = tf.Variable(tf.random_normal([5, 5]), name = 'weight6')
b6 = tf.Variable(tf.random_normal([5]), name = 'bias6')

W7 = tf.Variable(tf.random_normal([5, 5]), name = 'weight7')
b7 = tf.Variable(tf.random_normal([5]), name = 'bias7')

W8 = tf.Variable(tf.random_normal([5, 5]), name = 'weight8')
b8 = tf.Variable(tf.random_normal([5]), name = 'bias8')

W9 = tf.Variable(tf.random_normal([5, 5]), name = 'weight9')
b9 = tf.Variable(tf.random_normal([5]), name = 'bias9')

W10 = tf.Variable(tf.random_normal([5, 1]), name = 'weight10')
b10 = tf.Variable(tf.random_normal([1]), name = 'bias10')

In [18]:
def hypothesis():
    layer1 = tf.nn.relu(tf.matmul(x_data, W1) + b1)
    layer2 = tf.nn.relu(tf.matmul(layer1, W2) + b2)
    layer3 = tf.nn.relu(tf.matmul(layer2, W3) + b3)
    layer4 = tf.nn.relu(tf.matmul(layer3, W4) + b4)
    layer5 = tf.nn.relu(tf.matmul(layer4, W5) + b5)
    layer6 = tf.nn.relu(tf.matmul(layer5, W6) + b6)
    layer7 = tf.nn.relu(tf.matmul(layer6, W7) + b7)
    layer8 = tf.nn.relu(tf.matmul(layer7, W8) + b8)
    layer9 = tf.nn.relu(tf.matmul(layer8, W9) + b9)
    cost = tf.sigmoid(tf.matmul(layer9, W10) + b10)

    return cost
    

In [19]:
cost = -tf.reduce_mean(y_data * tf.log(hypothesis()) + (1 - y_data) * tf.log(1 - hypothesis()))
train = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [20]:
predicted = tf.cast(hypothesis() > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, y_data), dtype = tf.float32))

In [21]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(1001):
        sess.run(train, feed_dict = {X: x_data, Y: y_data})

        if step % 100 == 0:
            print("step = ", step, "cost = ", sess.run(cost, feed_dict = {X: x_data, Y: y_data}),sess.run(W2))
    h, c, a = sess.run([hypothesis(), predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

step =  0 cost =  0.71622705 [[ 1.0254498  -1.0860786   0.26425552  0.3823337   1.0479139 ]
 [-0.49248424 -0.9744123  -1.4663627   0.02379355  0.55209035]
 [-1.2831033   0.6591696   1.3149027  -0.37441415 -0.9767244 ]
 [-1.2465814  -0.3392333   0.24129823  1.0436403   0.07003616]
 [ 0.45342574 -0.6465525   0.39732793 -3.1424086  -0.14653848]]
step =  100 cost =  0.40890318 [[ 1.009751   -1.0860786   0.30702835  0.38845417  1.0521133 ]
 [-0.49248424 -0.9744123  -1.4663627   0.02379355  0.55209035]
 [-1.2863944   0.6591696   1.3277533  -0.3747088  -0.9853517 ]
 [-1.2549876  -0.3392333   0.24129823  1.0523641   0.05683164]
 [ 0.43812063 -0.6465525   0.45315224 -3.1427925  -0.18968517]]
step =  200 cost =  0.13243383 [[ 0.9944789  -1.0860786   0.30882335  0.39946932  1.0526706 ]
 [-0.49248424 -0.9744123  -1.4663627   0.02379355  0.55209035]
 [-1.2883245   0.6591696   1.3445041  -0.37486538 -0.9944677 ]
 [-1.2651166  -0.3392333   0.24129148  1.0623606   0.03755357]
 [ 0.42806962 -0.6465525 